#!/usr/bin/env python3
"""E-Ink Picture Client — fetches rendered preview from server and displays on E-Ink."""

import hashlib
import logging
import os
import signal
import sys
import time
from io import BytesIO
from typing import Optional, Tuple, Union

import requests
from PIL import Image

import config

logging.basicConfig(
    level=getattr(logging, config.LOG_LEVEL),
    format="%(asctime)s [%(levelname)s] %(message)s"
)
logger = logging.getLogger("eink-client")

# Display driver (loaded lazily)
epd = None
driver_name = config.DISPLAY_DRIVER

# Auth failure state: the 401 hint is logged once per state change,
# not on every poll iteration.
_auth_error_logged = False

# Content-skip state (E5.2). In-memory only by design: a process restart
# always writes the first frame (no persisted hash).
_last_fetch_hash: Optional[str] = None  # SHA-256 of the last fetched /preview wire bytes
_last_displayed_hash: Optional[str] = None  # hash of the last image successfully written to the panel
_last_panel_write_monotonic: Optional[float] = None  # time.monotonic() of that write

# Watchdog & recovery state (E5.4). In-memory only by design: a fresh process
# (systemd restart) starts with a clean slate and a fresh driver import.
_preview_only: bool = False  # ImportError at driver load: permanent preview mode
_hw_recovery_pending: bool = False  # driver down after a HW error; re-load next cycle
_consecutive_hw_failures: int = 0  # reset only on a successful physical panel write
_initial_display_done: bool = False  # first successful display run since process start


def _auth_headers() -> dict:
    """Headers for server requests: X-Client-Token when a token is configured.

    An empty token means no header at all (transitional state: server
    without authentication behaves exactly like before).
    """
    if config.CLIENT_TOKEN:
        return {"X-Client-Token": config.CLIENT_TOKEN}
    return {}


def _track_auth_state(resp: requests.Response) -> None:
    """Log a clear hint once when the server starts answering 401 Unauthorized."""
    global _auth_error_logged
    if resp.status_code == 401:
        if not _auth_error_logged:
            logger.error(
                "Server rejected request with 401 Unauthorized - authentication "
                "is enabled on the server but this client has no valid token. "
                "Set EINK_CLIENT_TOKEN in the client .env to the same value as "
                "the server's EINK_CLIENT_TOKEN (generated by setup.sh) and "
                "restart the client."
            )
            _auth_error_logged = True
    elif _auth_error_logged:
        logger.info("Server accepted request again - authentication recovered")
        _auth_error_logged = False


def _server_get(
    path: str, timeout: Union[float, Tuple[float, float]]
) -> requests.Response:
    """GET a server endpoint with auth headers and 401 state tracking.

    timeout accepts a scalar or a (connect, read) tuple - the long-polling
    status request uses the tuple form to keep a short connect timeout while
    allowing a long read.
    """
    resp = requests.get(
        f"{config.SERVER_URL}{path}", headers=_auth_headers(), timeout=timeout
    )
    _track_auth_state(resp)
    return resp


def _server_post(path: str, payload: dict, timeout: int) -> requests.Response:
    """POST to a server endpoint with auth headers and 401 state tracking."""
    resp = requests.post(
        f"{config.SERVER_URL}{path}",
        json=payload,
        headers=_auth_headers(),
        timeout=timeout,
    )
    _track_auth_state(resp)
    return resp


def _module_exit_best_effort() -> None:
    """Call epdconfig.module_exit() for the loaded driver, ignoring all errors.

    module_exit() closes SPI and pulls RST/DC/PWR low - the panel power is
    hard off afterwards. That is the safe end state after a hardware error;
    a deep-sleep command over a broken SPI bus would be a silent no-op.
    """
    try:
        if driver_name == "epd7in3e":
            from waveshare_epd import epd7in3e
            epd7in3e.epdconfig.module_exit()
        elif driver_name == "epd7in5_V2":
            from waveshare_epd import epd7in5_V2
            epd7in5_V2.epdconfig.module_exit()
    except Exception:
        pass


def _reset_display_driver() -> None:
    """Full driver reset after a hardware error (E5.4).

    Best-effort module_exit() (panel power off), then discard the epd object.
    The next refresh cycle re-instantiates EPD() from the CACHED module -
    importlib.reload is forbidden here: a reloaded epdconfig would construct
    a second RaspberryPi() while the old gpiozero objects still hold the
    pins (GPIOPinInUse).
    """
    global epd, _hw_recovery_pending
    _module_exit_best_effort()
    epd = None
    _hw_recovery_pending = True


def _register_hw_failure() -> None:
    """Count a consecutive hardware failure cycle; escalate to systemd at the limit.

    HW_FAILURE_LIMIT <= 0 disables the escalation (per-cycle recovery still
    runs). At the limit the process exits non-zero: Restart=always +
    RestartSec=10 bring up a fresh process with a freshly imported driver
    stack, which heals stuck in-process driver state.
    """
    global _consecutive_hw_failures
    _consecutive_hw_failures += 1
    logger.warning(
        "hardware failure cycle %d (limit %d, 0 = never escalate)",
        _consecutive_hw_failures, config.HW_FAILURE_LIMIT,
    )
    if config.HW_FAILURE_LIMIT > 0 and _consecutive_hw_failures >= config.HW_FAILURE_LIMIT:
        logger.critical(
            "too many consecutive display failures (%d) - exiting for systemd restart",
            _consecutive_hw_failures,
        )
        raise SystemExit(1)


def load_display_driver(name: str) -> None:
    """Dynamically load the correct Waveshare EPD driver.

    ImportError => permanent preview-only mode (no hardware libs installed;
    no recovery, no escalation). Any OTHER exception - epdconfig import side
    effects can raise BadPinFactory/GPIOPinInUse/RuntimeError, spidev raises
    OSError - is treated as a transient hardware failure: full traceback via
    logger.exception, driver reset, re-load attempt on the next cycle.
    """
    global epd, driver_name, _preview_only, _hw_recovery_pending
    driver_name = name
    logger.info("Loading display driver: %s", name)
    try:
        if name == "epd7in3e":
            from waveshare_epd import epd7in3e
            epd = epd7in3e.EPD()
        elif name == "epd7in5_V2":
            from waveshare_epd import epd7in5_V2
            epd = epd7in5_V2.EPD()
        else:
            logger.error("Unknown display driver: %s", name)
            return
        _preview_only = False
        _hw_recovery_pending = False
        logger.info("Display driver loaded: %s", name)
    except ImportError:
        logger.warning("Waveshare EPD library not found - running in preview-only mode")
        epd = None
        _preview_only = True
        _hw_recovery_pending = False
    except Exception:
        logger.exception("display recovery: driver reset after error")
        _reset_display_driver()


def _normalize_panel_image_mode(value: object) -> str:
    """Normalize the panel_image_mode setting to a known value.

    Only "original" selects the ungedithered raw panel image; every other
    value — including missing, empty, or an unexpected string — falls back to
    the dithered default. An older server that does not know the field must
    never break the client.
    """
    return "original" if value == "original" else "dithered"


def fetch_display_config() -> dict:
    """Fetch display config from server settings.

    panel_image_mode is a TOP-LEVEL setting (sibling of render_quality), not
    part of the nested display object, so it is surfaced into the returned dict
    here — no second HTTP request. Callers pass display_config["panel_image_mode"]
    down to fetch_preview to pick the wire endpoint.
    """
    try:
        resp = _server_get("/settings", timeout=5)
        if resp.ok:
            settings = resp.json()
            display = settings.get("display", {})
            driver = display.get("driver", config.DISPLAY_DRIVER)
            if driver != driver_name:
                load_display_driver(driver)
            display["panel_image_mode"] = _normalize_panel_image_mode(
                settings.get("panel_image_mode")
            )
            return display
    except Exception as e:
        logger.warning("Could not fetch display settings: %s", e)
    return {}


def fetch_preview(panel_image_mode: str = "dithered") -> Optional[Image.Image]:
    """Fetch rendered preview PNG from server.

    panel_image_mode == "original" requests the ungedithered raw panel image
    (/preview?raw=true); any other value requests the server-dithered default
    (/preview). The chosen wire bytes are what get hashed below, so a mode
    switch changes the content hash and triggers exactly one extra refresh
    before the skip (E5.2) goes quiet again.

    On success, records the SHA-256 of the raw wire bytes in
    _last_fetch_hash — the comparison point for the content skip (E5.2),
    computed before any Pillow decode.
    """
    global _last_fetch_hash
    try:
        path = "/preview?raw=true" if panel_image_mode == "original" else "/preview"
        resp = _server_get(path, timeout=30)
        resp.raise_for_status()
        content = resp.content
        content_hash = hashlib.sha256(content).hexdigest()
        img = Image.open(BytesIO(content))
        _last_fetch_hash = content_hash
        logger.info("Preview fetched: %dx%d, mode=%s", img.size[0], img.size[1], img.mode)
        return img
    except requests.ConnectionError:
        logger.warning("Server not reachable: %s", config.SERVER_URL)
    except Exception as e:
        logger.error("Failed to fetch preview: %s", e)
    return None


def save_last_sent_artifact(img: Image.Image) -> None:
    """Atomically save the exact image passed to the EPD driver as a PNG debug artifact.

    Writes to a temp file in the same directory as the target and renames via
    os.replace(), so a concurrent scp never sees a half-written PNG. Any write
    failure is logged as a warning and never interrupts the display refresh.
    """
    last_sent_path = config.LAST_SENT_PATH
    tmp_path = f"{last_sent_path}.tmp"
    try:
        img.save(tmp_path, format="PNG")
        os.replace(tmp_path, last_sent_path)
        logger.debug("Last-sent artifact written to %s", last_sent_path)
    except Exception as e:
        logger.warning("Failed to write last-sent artifact to %s: %s", last_sent_path, e)
        try:
            os.remove(tmp_path)
        except OSError:
            pass


def display_image(img: Image.Image, display_config: dict) -> bool:
    """Send image to E-Ink display via SPI."""
    if not epd:
        img.save("preview_output.png")
        logger.info("No display hardware - preview saved to preview_output.png")
        return True

    try:
        logger.info("Initializing display...")
        # epd7in3e/epd7in5_V2 return -1 when module_init() fails. Deliberately
        # only == -1 (not != 0): MockEPD returns None, the real drivers 0.
        if epd.init() == -1:
            raise RuntimeError("display init() returned -1 (module_init failed)")

        display_width = epd.width
        display_height = epd.height
        if img.size != (display_width, display_height):
            # Size mismatch signals a misconfiguration (wrong display profile
            # or wrong server). Log the actual size before resizing.
            logger.warning(
                "Preview size %dx%d does not match display %dx%d - "
                "resizing with NEAREST (check server display settings)",
                img.size[0], img.size[1], display_width, display_height,
            )
            # The server output is already dithered to the panel palette.
            # NEAREST is the only resample that keeps palette colors intact,
            # explicitly for all image modes - do not rely on Pillow's silent
            # P-mode resample coercion.
            img = img.resize((display_width, display_height), Image.Resampling.NEAREST)

        colors = display_config.get("colors", ["#000000", "#FFFFFF"])
        if len(colors) > 2:
            # 6-color display: convert to RGB, driver handles palette internally
            if img.mode != "RGB":
                img = img.convert("RGB")
            logger.info("Sending to %d-color display...", len(colors))
        else:
            # B/W display: server already applied Floyd-Steinberg dithering,
            # so convert without additional dithering to preserve quality
            if img.mode != "1":
                img = img.convert("L").point(lambda x: 0 if x < 128 else 255, "1")
            logger.info("Sending to B/W display...")

        save_last_sent_artifact(img)

        epd.display(epd.getbuffer(img))

        logger.info("Display entering sleep mode...")
        epd.sleep()
        logger.info("Display updated successfully")
        return True
    except Exception:
        # E5.4 recovery: full traceback, NO epd.sleep() over a possibly broken
        # SPI bus - module_exit() (panel power hard off) is the safe end state.
        # Return contract for callers/E5.2 unchanged: False => no hash update,
        # no heartbeat. Stable log line below is the HIL grep base.
        logger.exception("display recovery: driver reset after error")
        _reset_display_driver()
        return False


def get_refresh_status() -> dict:
    """Long-poll /api/refresh_status; empty dict on any error.

    The server holds this request open (up to ~25s) and answers the moment a
    manual trigger fires, so the read timeout must exceed the server hold
    (config.LONGPOLL_TIMEOUT, default 30s > 25s). A short 5s connect timeout
    still fails fast when the server is unreachable.
    """
    try:
        resp = _server_get(
            "/api/refresh_status", timeout=(5, config.LONGPOLL_TIMEOUT)
        )
        if resp.ok:
            data = resp.json()
            if isinstance(data, dict):
                return data
    except Exception:
        pass
    return {}


def check_should_refresh() -> bool:
    """Ask server if display should refresh."""
    return bool(get_refresh_status().get("should_refresh", False))


def _max_skip_elapsed() -> bool:
    """True when the last real panel write is older than MAX_SKIP_HOURS.

    Measured with time.monotonic() (immune to wall-clock jumps).
    MAX_SKIP_HOURS <= 0 disables the guard.
    """
    if config.MAX_SKIP_HOURS <= 0:
        return False
    if _last_panel_write_monotonic is None:
        return True
    return time.monotonic() - _last_panel_write_monotonic > config.MAX_SKIP_HOURS * 3600


def _should_skip_panel_write(content_hash: Optional[str], reason: Optional[str]) -> bool:
    """Decide whether the physical panel write can be skipped (E5.2).

    Conservative: skip ONLY when ALL conditions hold — content skip enabled,
    hardware present, interval-driven refresh (reason "manual" or missing =>
    always write), hash identical to the last successfully displayed image,
    and the panel-care guard (MAX_SKIP_HOURS) not expired.
    """
    if not config.CONTENT_SKIP:
        return False
    if epd is None:
        return False
    if reason != "interval":
        return False
    if content_hash is None or _last_displayed_hash is None:
        return False
    if content_hash != _last_displayed_hash:
        return False
    if _max_skip_elapsed():
        return False
    return True


def _record_panel_write(content_hash: Optional[str]) -> None:
    """Remember hash and time of a successful physical panel write.

    In-memory only (a restart always writes). No-op without hardware: the
    preview-only path must never feed the skip decision. A successful
    physical write is also the ONLY event that resets the E5.4 hardware
    failure counter (skips, network errors and preview-only leave it alone).
    """
    global _last_displayed_hash, _last_panel_write_monotonic, _consecutive_hw_failures
    if epd is None:
        return
    _last_displayed_hash = content_hash
    _last_panel_write_monotonic = time.monotonic()
    _consecutive_hw_failures = 0


def send_heartbeat(status: str = "refreshed") -> None:
    """Tell server that the display content is current ("refreshed" or "skipped")."""
    try:
        _server_post(
            "/api/client_heartbeat",
            {
                "status": status,
                "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            },
            timeout=5,
        )
    except Exception:
        pass


def handle_refresh(display_config: dict, reason: Optional[str]) -> bool:
    """Fetch the current preview and update the panel, honoring the content skip.

    Returns True when the cycle made forward progress - a heartbeat was sent
    ("refreshed" after a panel write, "skipped" on a content skip). The
    heartbeat advances the server's LastClientRefresh, so the next poll blocks
    on the server hold or reports no work. Returns False when NO heartbeat was
    sent (hardware failure, unreachable preview, failed write): the caller must
    pace the next poll, otherwise the server keeps returning should_refresh=true
    and the loop busy-spins.

    Skip path: no epd.init/display/sleep (panel stays in deep sleep), the
    last-sent artifact is left untouched, heartbeat is sent with "skipped".
    The hash is recorded only AFTER a successful panel write; a display
    failure leaves it unchanged so the next cycle writes again.

    E5.4 recovery: after a hardware error the driver is re-instantiated from
    the cached module before the write attempt; a failed re-load counts as a
    hardware failure cycle. Network errors touch neither panel nor counter.
    """
    global _initial_display_done
    if epd is None and _hw_recovery_pending:
        load_display_driver(driver_name)
        if epd is None and _hw_recovery_pending:
            _register_hw_failure()
            return False
    img = fetch_preview(display_config.get("panel_image_mode", "dithered"))
    if img is None:
        logger.warning("Failed to fetch preview for refresh")
        return False
    content_hash = _last_fetch_hash
    if _should_skip_panel_write(content_hash, reason):
        logger.info("skipping panel refresh (content unchanged)")
        send_heartbeat("skipped")
        return True
    if display_image(img, display_config):
        _initial_display_done = True
        _record_panel_write(content_hash)
        send_heartbeat("refreshed")
        return True
    _register_hw_failure()
    return False


def process_refresh_cycle() -> bool:
    """One long-poll cycle: ask the server and refresh the panel if needed.

    Returns True when the caller may re-poll immediately: a 2xx status poll
    that either had nothing due (should_refresh=false - the server already held
    the request open ~25s) or made forward progress (handle_refresh sent a
    heartbeat). Returns False when the caller must apply the bounded reconnect
    backoff: the poll failed (network error / timeout / non-2xx), OR a refresh
    was due but the cycle made NO progress (no heartbeat). The latter is
    critical: should_refresh=true is answered by the server immediately (the
    ~25s hold only covers should_refresh=false), so a due-but-stuck cycle that
    re-polls at once would busy-loop until a heartbeat advances the server's
    LastClientRefresh - backing off restores the pre-B3 pacing for those cases
    (fresh boot with no image yet, a failed manual write, a hardware failure).

    Initial retry (E5.4): until the first successful display run since
    process start, every cycle behaves like the startup path - unconditional
    fetch + write, should_refresh/reason are ignored. This closes the
    power-outage gap when the very first fetch hits the server before it
    listens. From the first success on, exactly today's semantics apply.
    """
    status = get_refresh_status()
    # get_refresh_status() returns {} on any error and a populated dict
    # (always carrying should_refresh) on a real 2xx response: an empty dict
    # therefore means "no usable poll response -> reconnect backoff".
    poll_ok = bool(status)
    if not _initial_display_done:
        logger.info("initial display update pending - retrying unconditionally")
        display_config = fetch_display_config()
        # The initial retry always attempts a write, so it is always "due":
        # re-poll immediately only if it actually made progress (a heartbeat),
        # otherwise back off so a fresh boot with no image yet does not spin.
        made_progress = handle_refresh(display_config, None)
        return poll_ok and made_progress
    if not status.get("should_refresh", False):
        return poll_ok
    logger.info("Server says: refresh needed")
    display_config = fetch_display_config()
    # A due refresh may re-poll immediately only when it made progress;
    # otherwise pace the next poll so a stuck refresh does not busy-loop.
    made_progress = handle_refresh(display_config, status.get("reason"))
    return poll_ok and made_progress


def cleanup() -> None:
    """Clean shutdown — put display to sleep and release GPIO."""
    if epd:
        try:
            epd.sleep()
        except Exception:
            pass
        _module_exit_best_effort()


def main() -> None:
    """Main loop: poll server for refresh status, fetch preview, display, repeat."""
    global _initial_display_done
    logger.info("E-Ink Client starting - Server: %s, Driver: %s", config.SERVER_URL, config.DISPLAY_DRIVER)

    running = True

    def shutdown(signum, frame):
        nonlocal running
        logger.info("Shutting down...")
        running = False

    signal.signal(signal.SIGINT, shutdown)
    signal.signal(signal.SIGTERM, shutdown)

    # Initial setup: load driver and fetch config
    _initial_display_done = False
    load_display_driver(config.DISPLAY_DRIVER)

    # try/finally so cleanup() also runs when the E5.4 escalation raises
    # SystemExit(1) out of the poll loop.
    try:
        display_config = fetch_display_config()
        if not display_config:
            display_config = {}

        # Initial display update (always unconditional, spec E5.2 fact 8)
        logger.info("Performing initial display update...")
        if epd is None and _hw_recovery_pending:
            # Driver load failed hard at startup (non-ImportError): counts as
            # one hardware failure cycle; the poll loop retries the load.
            _register_hw_failure()
        else:
            img = fetch_preview(display_config.get("panel_image_mode", "dithered"))
            if img:
                if display_image(img, display_config):
                    _initial_display_done = True
                    _record_panel_write(_last_fetch_hash)
                    send_heartbeat()
                else:
                    _register_hw_failure()
            else:
                logger.warning("No image on startup - will retry on next poll")

        # Main long-poll loop: the server holds GET /api/refresh_status open
        # and answers the moment a manual trigger fires (or after its bounded
        # hold), so a genuinely-actioned poll is followed by an immediate
        # re-poll - the server hold, not a client sleep, provides the pacing.
        # This is what makes a manual "Refresh Display" reach the panel in ~2s.
        #
        # POLL_INTERVAL is no longer a happy-path delay: it is only the bounded
        # backoff used when the poll fails OR a due refresh made no forward
        # progress (no heartbeat). Without that second case the loop would spin,
        # because should_refresh=true is answered immediately (no 25s hold).
        poll_interval = config.POLL_INTERVAL
        logger.info("Entering long-poll loop (reconnect backoff %ds)", poll_interval)

        while running:
            repoll_now = process_refresh_cycle()

            if not running:
                break

            if not repoll_now:
                # Failed poll, or a due refresh that made no progress: back off
                # POLL_INTERVAL seconds (checked once per second for a
                # responsive shutdown) instead of hammering the server.
                for _ in range(poll_interval):
                    if not running:
                        break
                    time.sleep(1)
    finally:
        cleanup()
        logger.info("Client stopped")


if __name__ == "__main__":
    main()
