#!/usr/bin/env python3
"""E-Ink Picture Client — fetches rendered preview from server and displays on E-Ink."""

import logging
import os
import signal
import sys
import time
from io import BytesIO
from typing import Optional

import requests
from PIL import Image

import config

logging.basicConfig(
    level=getattr(logging, config.LOG_LEVEL),
    format="%(asctime)s [%(levelname)s] %(message)s"
)
logger = logging.getLogger("eink-client")

# Display driver (loaded lazily)
epd = None
driver_name = config.DISPLAY_DRIVER

# Auth failure state: the 401 hint is logged once per state change,
# not on every poll iteration.
_auth_error_logged = False


def _auth_headers() -> dict:
    """Headers for server requests: X-Client-Token when a token is configured.

    An empty token means no header at all (transitional state: server
    without authentication behaves exactly like before).
    """
    if config.CLIENT_TOKEN:
        return {"X-Client-Token": config.CLIENT_TOKEN}
    return {}


def _track_auth_state(resp: requests.Response) -> None:
    """Log a clear hint once when the server starts answering 401 Unauthorized."""
    global _auth_error_logged
    if resp.status_code == 401:
        if not _auth_error_logged:
            logger.error(
                "Server rejected request with 401 Unauthorized - authentication "
                "is enabled on the server but this client has no valid token. "
                "Set EINK_CLIENT_TOKEN in the client .env to the same value as "
                "the server's EINK_CLIENT_TOKEN (generated by setup.sh) and "
                "restart the client."
            )
            _auth_error_logged = True
    elif _auth_error_logged:
        logger.info("Server accepted request again - authentication recovered")
        _auth_error_logged = False


def _server_get(path: str, timeout: int) -> requests.Response:
    """GET a server endpoint with auth headers and 401 state tracking."""
    resp = requests.get(
        f"{config.SERVER_URL}{path}", headers=_auth_headers(), timeout=timeout
    )
    _track_auth_state(resp)
    return resp


def _server_post(path: str, payload: dict, timeout: int) -> requests.Response:
    """POST to a server endpoint with auth headers and 401 state tracking."""
    resp = requests.post(
        f"{config.SERVER_URL}{path}",
        json=payload,
        headers=_auth_headers(),
        timeout=timeout,
    )
    _track_auth_state(resp)
    return resp


def load_display_driver(name: str):
    """Dynamically load the correct Waveshare EPD driver."""
    global epd, driver_name
    driver_name = name
    logger.info("Loading display driver: %s", name)
    try:
        if name == "epd7in3e":
            from waveshare_epd import epd7in3e
            epd = epd7in3e.EPD()
        elif name == "epd7in5_V2":
            from waveshare_epd import epd7in5_V2
            epd = epd7in5_V2.EPD()
        else:
            logger.error("Unknown display driver: %s", name)
            return
        logger.info("Display driver loaded: %s", name)
    except ImportError:
        logger.warning("Waveshare EPD library not found - running in preview-only mode")
        epd = None


def fetch_display_config() -> dict:
    """Fetch display config from server settings."""
    try:
        resp = _server_get("/settings", timeout=5)
        if resp.ok:
            settings = resp.json()
            display = settings.get("display", {})
            driver = display.get("driver", config.DISPLAY_DRIVER)
            if driver != driver_name:
                load_display_driver(driver)
            return display
    except Exception as e:
        logger.warning("Could not fetch display settings: %s", e)
    return {}


def fetch_preview() -> Optional[Image.Image]:
    """Fetch rendered preview PNG from server."""
    try:
        resp = _server_get("/preview", timeout=30)
        resp.raise_for_status()
        img = Image.open(BytesIO(resp.content))
        logger.info("Preview fetched: %dx%d, mode=%s", img.size[0], img.size[1], img.mode)
        return img
    except requests.ConnectionError:
        logger.warning("Server not reachable: %s", config.SERVER_URL)
    except Exception as e:
        logger.error("Failed to fetch preview: %s", e)
    return None


def save_last_sent_artifact(img: Image.Image) -> None:
    """Atomically save the exact image passed to the EPD driver as a PNG debug artifact.

    Writes to a temp file in the same directory as the target and renames via
    os.replace(), so a concurrent scp never sees a half-written PNG. Any write
    failure is logged as a warning and never interrupts the display refresh.
    """
    last_sent_path = config.LAST_SENT_PATH
    tmp_path = f"{last_sent_path}.tmp"
    try:
        img.save(tmp_path, format="PNG")
        os.replace(tmp_path, last_sent_path)
        logger.debug("Last-sent artifact written to %s", last_sent_path)
    except Exception as e:
        logger.warning("Failed to write last-sent artifact to %s: %s", last_sent_path, e)
        try:
            os.remove(tmp_path)
        except OSError:
            pass


def display_image(img: Image.Image, display_config: dict) -> bool:
    """Send image to E-Ink display via SPI."""
    if not epd:
        img.save("preview_output.png")
        logger.info("No display hardware - preview saved to preview_output.png")
        return True

    try:
        logger.info("Initializing display...")
        epd.init()

        display_width = epd.width
        display_height = epd.height
        if img.size != (display_width, display_height):
            # Size mismatch signals a misconfiguration (wrong display profile
            # or wrong server). Log the actual size before resizing.
            logger.warning(
                "Preview size %dx%d does not match display %dx%d - "
                "resizing with NEAREST (check server display settings)",
                img.size[0], img.size[1], display_width, display_height,
            )
            # The server output is already dithered to the panel palette.
            # NEAREST is the only resample that keeps palette colors intact,
            # explicitly for all image modes - do not rely on Pillow's silent
            # P-mode resample coercion.
            img = img.resize((display_width, display_height), Image.Resampling.NEAREST)

        colors = display_config.get("colors", ["#000000", "#FFFFFF"])
        if len(colors) > 2:
            # 6-color display: convert to RGB, driver handles palette internally
            if img.mode != "RGB":
                img = img.convert("RGB")
            logger.info("Sending to %d-color display...", len(colors))
        else:
            # B/W display: server already applied Floyd-Steinberg dithering,
            # so convert without additional dithering to preserve quality
            if img.mode != "1":
                img = img.convert("L").point(lambda x: 0 if x < 128 else 255, "1")
            logger.info("Sending to B/W display...")

        save_last_sent_artifact(img)

        epd.display(epd.getbuffer(img))

        logger.info("Display entering sleep mode...")
        epd.sleep()
        logger.info("Display updated successfully")
        return True
    except Exception as e:
        logger.error("Display error: %s", e)
        try:
            epd.sleep()
        except Exception:
            pass
        return False


def check_should_refresh() -> bool:
    """Ask server if display should refresh."""
    try:
        resp = _server_get("/api/refresh_status", timeout=5)
        if resp.ok:
            data = resp.json()
            return data.get("should_refresh", False)
    except Exception:
        pass
    return False


def send_heartbeat() -> None:
    """Tell server that display was updated."""
    try:
        _server_post(
            "/api/client_heartbeat",
            {
                "status": "refreshed",
                "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            },
            timeout=5,
        )
    except Exception:
        pass


def cleanup() -> None:
    """Clean shutdown — put display to sleep and release GPIO."""
    if epd:
        try:
            epd.sleep()
        except Exception:
            pass
        try:
            if driver_name == "epd7in3e":
                from waveshare_epd import epd7in3e
                epd7in3e.epdconfig.module_exit()
            elif driver_name == "epd7in5_V2":
                from waveshare_epd import epd7in5_V2
                epd7in5_V2.epdconfig.module_exit()
        except Exception:
            pass


def main() -> None:
    """Main loop: poll server for refresh status, fetch preview, display, repeat."""
    logger.info("E-Ink Client starting - Server: %s, Driver: %s", config.SERVER_URL, config.DISPLAY_DRIVER)

    running = True

    def shutdown(signum, frame):
        nonlocal running
        logger.info("Shutting down...")
        running = False

    signal.signal(signal.SIGINT, shutdown)
    signal.signal(signal.SIGTERM, shutdown)

    # Initial setup: load driver and fetch config
    load_display_driver(config.DISPLAY_DRIVER)
    display_config = fetch_display_config()
    if not display_config:
        display_config = {}

    # Initial display update
    logger.info("Performing initial display update...")
    img = fetch_preview()
    if img:
        if display_image(img, display_config):
            send_heartbeat()
    else:
        logger.warning("No image on startup - will retry on next poll")

    # Main poll loop
    poll_interval = config.POLL_INTERVAL
    logger.info("Entering poll loop (every %ds)", poll_interval)

    while running:
        for _ in range(poll_interval):
            if not running:
                break
            time.sleep(1)

        if not running:
            break

        if check_should_refresh():
            logger.info("Server says: refresh needed")
            display_config = fetch_display_config()
            img = fetch_preview()
            if img:
                if display_image(img, display_config):
                    send_heartbeat()
            else:
                logger.warning("Failed to fetch preview for refresh")

    cleanup()
    logger.info("Client stopped")


if __name__ == "__main__":
    main()
